### ISSUE TITLE
I have a question when I run make inside the root folder,'start_color' has not defined,but I already install the curse.h library，why?

### ISSUE THREAD

**Issue by h0rs3fa11** [alexandernst/monks#48]

**Comment by alexandernst** [comment]
Can you copy the output?

**Comment by qmaqma573** [comment]
monks-viewer.o：在函数‘main’中：
monks-viewer.c:(.text+0x24f)：对‘start_color’未定义的引用
monks-viewer.c:(.text+0x263)：对‘init_pair’未定义的引用
monks-viewer.c:(.text+0x277)：对‘init_pair’未定义的引用
monks-viewer.c:(.text+0x28b)：对‘init_pair’未定义的引用
monks-viewer.c:(.text+0x2ab)：对‘stdscr’未定义的引用
monks-viewer.c:(.text+0x2b3)：对‘wrefresh’未定义的引用
monks-viewer.c:(.text+0x496)：对‘endwin’未定义的引用
monks-viewer.o：在函数‘do_segfault’中：
monks-viewer.c:(.text+0x4b0)：对‘endwin’未定义的引用
collect2: 错误：ld 返回 1
make[1]: *** [../monks-viewer] 错误 1
make[1]: 离开目录“/root/文档/alexandernst-monks-9e7dd7c/monks”
make: *** [monks] 错误 2

**Comment by alexandernst** [comment]
Can you copy an english version of this? I don't understand Chinese, sorry.

**Comment by qmaqma573** [comment]
ok,I translate it
monks-viewer.o：in function ‘main’：
monks-viewer.c:(.text+0x24f)：Undefined reference to ‘start_color’
monks-viewer.c:(.text+0x263)：Undefined reference to‘init_pair’
monks-viewer.c:(.text+0x277)：Undefined reference to ‘init_pair'
monks-viewer.c:(.text+0x28b)：Undefined reference to ‘init_pair’
monks-viewer.c:(.text+0x2ab)：Undefined reference  to‘stdscr’ 
monks-viewer.c:(.text+0x2b3)：Undefined reference to ‘wrefresh’
monks-viewer.c:(.text+0x496)：Undefined reference to ‘endwin’
monks-viewer.o：in function ‘do_segfault’：
monks-viewer.c:(.text+0x4b0)：Undefined reference to ‘endwin’
collect2: error：ld return 1
make[1]: *** [../monks-viewer] error 1
make[1]:  leave the directory “/root/文档/alexandernst-monks-9e7dd7c/monks”
make: *** [monks] error 2

**Comment by alexandernst** [comment]
Undefined reference means your compiler isn't able to find ncurses. What distro are you using?

**Comment by qmaqma573** [comment]
centos 7

**Comment by alexandernst** [comment]
Ok, from what I see here http://rpmfind.net/linux/rpm2html/search.php?query=ncurses-devel you need `ncurses-devel-*`. Did you install that?

**Comment by qmaqma573** [comment]
It works! Thank you.
Can monks filter process name?

**Comment by alexandernst** [comment]
No, it currently only shows process names, but it can't filter them. Check the pending issues.
